### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [UserLeap/userleap-gtm-template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needs to be resolved ahead of approving the template for the gallery.

1) The documentation URL mentioned in the manifest file "https://https://docs.userleap.com" shows error "This site can’t be reached https’s server IP address could not be found".
2) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text arguement and return a URI Encoded string. You should use this method on "data.envId" when passing the url in injectScript
'https://cdn.userleap.com/shim.js?id='+data.envId
3) Please update injectScript api in the code as per [https://developers.google.com/tag-manager/templates/api#injectscript](https://developers.google.com/tag-manager/templates/api#injectscript) with success and failure functions

**Comment by squamos** [comment]
@praveena-pappu These issues have been resolved. Could you please re-review?

**Comment by squamos** [comment]
Checking in on this review @praveena-pappu - do you know when you'll have a moment to look at the new submission?

**Comment by praveena-pappu** [comment]
Thanks for submitting a template to the gallery, there were a few issues in your template that needs to be resolved ahead of approving the template for the gallery.

1) codeUriComponent should be used on **user provided values** that are then used as parameters in your url. These methods take in a single text arguement and return a URI Encoded string. You should use this method on **"data.envId"**  only when passing the url in injectScript
'https://cdn.userleap.com/shim.js?id='+data.envId

**Comment by squamos** [comment]
Hey @praveena-pappu - thanks for the quick review! I've tried doing what you suggested but I get the following error when I tried what you suggested: "Error in encodeUriComponent. Required argument uri not supplied."

```
injectScript('https://cdn.userleap.com/shim.js?id='+encodeUriComponent(data.envId), data.gtmOnSuccess, data.gtmOnFailure);
```

![image](https://user-images.githubusercontent.com/568010/82599532-59444200-9b61-11ea-867d-f75d616b55aa.png)

**Comment by squamos** [comment]
Hey @praveena-pappu any thoughts on this?

**Comment by squamos** [comment]
@praveena-pappu Checking in here - can you give me some more guidance here? I got an error when trying to follow your suggestion and only including user inputs as parameter to `encodeUriComponent` (see above). 

I've tested the template as it stands right now and it works like I would expect. Can we move forward with this?

**Comment by squamos** [comment]
@praveena-pappu any thoughts on this?

**Comment by delsonting** [comment]
Hi, there are two points of feedback here:

1) The data.envId variable is not required and if there is no value provided encodeUriComponent(data.envId) will throw an error. If this is a required field, you can specify the field as "This value cannot be empty" by adding it as a validation on the field and optionally provide a default value. If this field is not required, you will need to add logic to your code to handle this scenario.

![Screen Shot 2020-05-28 at 2 53 13 PM](https://user-images.githubusercontent.com/52263564/83197910-2666f480-a0f3-11ea-8f17-b97601c164da.png)


2) encodeUriComponent will encode the '=' character which may not be what you want here. If you want to pass this value as a url parameter, you move the 'id=' out of encodeUriComponent call. Example:
`injectScript('https://cdn.userleap.com/shim.js?id='+encodeUriComponent(data.envId), data.gtmOnSuccess, data.gtmOnFailure);`

**Comment by squamos** [comment]
Thank you @praveena-pappu. It looks like making envId required solved the problem. I've now resolved all the issue you've identified.

**Comment by praveena-pappu** [comment]
Thank you for the update. Please let us know if the new submission [https://github.com/UserLeap/userleap-gtm-tag](https://github.com/UserLeap/userleap-gtm-tag) is the new version of the template. 

Please let us know which one is the preferred template to go to gallery, as we see both refer to similar functionality.

**Comment by squamos** [comment]
Hey @praveena-pappu I'd like to replace this template submission with https://github.com/UserLeap/userleap-gtm-tag. The new userleap-gtm-tag submission includes all the functionality in this template and more

**Comment by squamos** [comment]
@praveena-pappu I've closed this issue since we'll be moving forward with the submission at https://github.com/UserLeap/userleap-gtm-tag. Please provide any further feedback there. Thank you!

**Comment by squamos** [comment]
Hey @praveena-pappu  Do you know when we'll be able to get feedback on the new tag @ https://github.com/UserLeap/userleap-gtm-tag ?

**Comment by praveena-pappu** [comment]
Hello as requested earlier, we have reviewed [https://github.com/UserLeap/userleap-gtm-tag](https://github.com/UserLeap/userleap-gtm-tag). Please refer to live version [https://tagmanager.google.com/gallery/#/owners/UserLeap/templates/userleap-gtm-tag](https://tagmanager.google.com/gallery/#/owners/UserLeap/templates/userleap-gtm-tag)
